<!-- Main Content -->
<div class="px-8 pt-8 pb-20 max-h-screen overflow-x-auto soft-scrollbar" x-data="{ modalOpen: @entangle('modalOpen') }">
    <div class="">
        <div class="text-xl mb-5 font-bold text-gray-700">Roadmaps for
            <span
                class="text-gray-100 bg-blue-500 p-1 capitalize inline-block -skew-y-3">{{ str_replace('_', ' ', auth()->user()->interest) }}</span>
        </div>

        <div class="grid grid-cols-2 gap-x-16 gap-y-5 my-8">
            @foreach ($roadmaps as $r)
                @php
                    $title = str_replace(['_', 'developer'], [' ', ''], $r->job_title);
                    $r->title = strtoupper($title);
                @endphp

                <div
                    class="p-6 rounded-xl shadow-[rgba(149,157,165,0.2)_0px_8px_24px] flex justify-between items-center gap-5 ">
                    <h1 class="text-lg font-semibold text-gray-700">{{ $r->title }}</h1>
                    <button wire:click="generateRoadmap('{{ $r->title }}')"
                        class="text-sm font-medium px-4 py-1.5 bg-gray-200 rounded-lg hover:bg-gray-300 transition">
                        Generate
                    </button>

                </div>
            @endforeach
        </div>
    </div>

    <div class="border-t pt-5 border-gray-300">
        <div class="text-xl mb-5 font-bold text-gray-700">Your generated roadmaps </div>

        <div class="grid grid-cols-2 gap-x-16 gap-y-6 my-8 pb-10">
            @if ($userRoadmaps)
                @foreach ($userRoadmaps as $userRoadmap)
                    <div
                        class="p-6 rounded-xl shadow-[rgba(149,157,165,0.2)_0px_8px_24px] flex justify-between items-center gap-5 ">
                        <h1 class="text-lg font-bold text-gray-700">{{ $userRoadmap->technology }} </h1>
                        <div class="flex flex-col items-end gap-y-4 w-1/3">
                            @php
                                $progress = 0;
                                $sections = '0/3';
                                if ($userRoadmap->beginner_completed == true) {
                                    $progress += 30;
                                    $sections = '1/3';
                                }
                                if ($userRoadmap->intermediate_completed == true) {
                                    $progress += 40;
                                    $sections = '2/3';
                                }
                                if ($userRoadmap->advanced_completed == true) {
                                    $progress += 30;
                                    $sections = '3/3';
                                }
                            @endphp
                            {{-- Progress: {{ $progress }}% --}}

                            <div class="w-full bg-gray-200 rounded-full ">
                                <div class="bg-blue-500 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-full"
                                    style="width: {{ $progress }}%"> {{ $sections }}</div>
                            </div>

                            <button wire:click="viewRoadmap({{ $userRoadmap->id }})"
                                class="text-sm font-medium px-4 py-1.5 bg-gray-200 rounded-lg hover:bg-gray-300 transition">
                                View
                            </button>
                        </div>
                    </div>
                @endforeach
                {{-- @else --}}
                @if ($userRoadmaps->isEmpty())
                    <div class="text-base text-blue-500 col-span-2 text-center">No roadmaps generated yet!</div>
                @endif
            @endif
        </div>
    </div>

    {{-- roadmap loader --}}
    <div wire:loading wire:target="generateRoadmap" class="fixed inset-0 flex items-center justify-center z-40">
        <!-- Background with blur -->
        <div class="fixed inset-0 bg-gray-50 bg-opacity-75 backdrop-blur"></div>

        <!-- Loader -->
        <div class="loader flex items-center justify-center h-screen text-white relative z-50">
            <div class="relative flex flex-col space-y-4 w-1/2 animate-pulse gap-4 p-4">
                <h1 class="text-xl font-semibold text-gray-700">Please wait! Your roadmap is being generated by AI...
                </h1>
                <div class="h-9 w-3/5 rounded-xl bg-slate-400 text-lg"></div>

                <div>
                    <div class="h-9 w-2/5 rounded-xl bg-slate-400 mb-2"></div>
                    <ul class="space-y-2">
                        <li class="flex justify-between">
                            <div class="h-6 w-3/4 rounded-xl bg-slate-400"></div>
                            <div class="h-6 w-1/6 rounded-xl bg-slate-400"></div>
                        </li>
                        <li class="flex justify-between">
                            <div class="h-6 w-3/4 rounded-xl bg-slate-400"></div>
                            <div class="h-6 w-1/6 rounded-xl bg-slate-400"></div>
                        </li>
                        <li class="flex justify-between">
                            <div class="h-6 w-3/4 rounded-xl bg-slate-400"></div>
                            <div class="h-6 w-1/6 rounded-xl bg-slate-400"></div>
                        </li>
                        <li class="flex justify-between">
                            <div class="h-6 w-3/4 rounded-xl bg-slate-400"></div>
                            <div class="h-6 w-1/6 rounded-xl bg-slate-400"></div>
                        </li>
                        <li class="flex justify-between">
                            <div class="h-6 w-3/4 rounded-xl bg-slate-400"></div>
                            <div class="h-6 w-1/6 rounded-xl bg-slate-400"></div>
                        </li>
                    </ul>
                </div>

                <div>
                    <div class="h-9 w-2/5 rounded-xl bg-slate-400 mb-3"></div>
                    <ul class="space-y-4">
                        <li class="flex justify-between">
                            <div class="h-6 w-3/4 rounded-xl bg-slate-400"></div>
                            <div class="h-6 w-1/6 rounded-xl bg-slate-400"></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    {{-- roadmap modal --}}
    <div x-show="modalOpen" class="fixed inset-0 z-50 " aria-labelledby="modal-title" role="dialog" aria-modal="true">
        <div class="flex items-end justify-center min-h-screen px-4 text-center md:items-center sm:block sm:p-0">
            <div x-cloak @click="modalOpen = false" x-show="modalOpen"
                x-transition:enter="transition ease-out duration-400 transform" x-transition:enter-start="opacity-0"
                x-transition:enter-end="opacity-100" x-transition:leave="transition ease-in duration-200 transform"
                x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0"
                class="fixed inset-0 transition-opacity bg-gray-500 bg-opacity-40" aria-hidden="true">
            </div>

            <div x-cloak x-show="modalOpen" x-transition:enter="transition ease-out duration-400 transform"
                x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100"
                x-transition:leave="transition ease-in duration-200 transform"
                x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100"
                x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                class="relative soft-scrollbar inline-block w-full p-4 my-20 overflow-y-auto text-left transition-all transform bg-white rounded-lg shadow-xl max-w-xl lg:max-w-3xl max-h-[80vh]">



                <div class="flex items-center justify-between space-x-4 ">
                    <h1 class="text-xl text-gray-800">Generated by AI</h1>

                    <button @click="modalOpen = false" class="text-gray-600 focus:outline-none hover:text-gray-700">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </button>
                </div>

                {{-- statusess --}}
                @if ($viewRoadmapContent)
                    <ul class="mt-4 mx-4 text-sm bg-white flex items-center justify-between">
                        <li>
                            <input type="checkbox" wire:click="updateStatus('beginner')" id="beginner_completed"
                                class="hidden peer" @if ($beginner_completed) Checked @endif>
                            <label for="beginner_completed"
                                class="inline-flex items-center font-semibold text-sm justify-between w-full px-3 py-1.5 text-gray-500 bg-white border-2 border-gray-200 rounded-xl cursor-pointer  peer-checked:border-green-600 hover:text-gray-600  peer-checked:text-green-600  hover:bg-gray-50 ">
                                Beginner Completed
                                <svg class="ml-2 @if (!$beginner_completed) hidden @endif"
                                    xmlns="http://www.w3.org/2000/svg" version="1.1"
                                    xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" x="0"
                                    y="0" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512"
                                    xml:space="preserve" class="">
                                    <g>
                                        <path fill="#2AD352"
                                            d="M256 0C114.62 0 0 114.58 0 256s114.62 256 256 256 256-114.65 256-256S397.38 0 256 0z"
                                            opacity="1" data-original="#2ad352" class=""></path>
                                        <path fill="#74DA7F"
                                            d="M0 256a254.87 254.87 0 0 0 30.49 121.23 278.76 278.76 0 0 0 78.73 11.29c153.9 0 278.66-124.76 278.66-278.66a278.7 278.7 0 0 0-11.64-79.94A254.86 254.86 0 0 0 256 0C114.62 0 0 114.58 0 256z"
                                            opacity="1" data-original="#74da7f" class=""></path>
                                        <path fill="#FFFFFF"
                                            d="M402 213.58 248.13 375.17a45.16 45.16 0 0 1-32.48 14h-.2a45.11 45.11 0 0 1-32.4-13.71l-81.65-84.1a45.14 45.14 0 1 1 64.78-62.87l48.95 50.42 121.49-127.58A45.14 45.14 0 1 1 402 213.58z"
                                            opacity="1" data-original="#ffffff" class=""></path>
                                    </g>
                                </svg>
                            </label>
                        </li>
                        <li>
                            <input type="checkbox" wire:click="updateStatus('intermediate')"
                                id="intermediate_completed" class="hidden peer"
                                @if ($intermediate_completed) Checked @endif
                                @if (!$beginner_completed) disabled @endif>
                            <label for="intermediate_completed"
                                class="inline-flex items-center font-semibold text-sm justify-between w-full px-3 py-1.5 text-gray-500 bg-white border-2 border-gray-200 rounded-xl cursor-pointer  peer-checked:border-green-600 hover:text-gray-600  peer-checked:text-green-600  hover:bg-gray-50 ">
                                Intermediate Completed
                                <svg class="ml-2 @if (!$intermediate_completed) hidden @endif"
                                    xmlns="http://www.w3.org/2000/svg" version="1.1"
                                    xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" x="0"
                                    y="0" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512"
                                    xml:space="preserve" class="">
                                    <g>
                                        <path fill="#2AD352"
                                            d="M256 0C114.62 0 0 114.58 0 256s114.62 256 256 256 256-114.65 256-256S397.38 0 256 0z"
                                            opacity="1" data-original="#2ad352" class=""></path>
                                        <path fill="#74DA7F"
                                            d="M0 256a254.87 254.87 0 0 0 30.49 121.23 278.76 278.76 0 0 0 78.73 11.29c153.9 0 278.66-124.76 278.66-278.66a278.7 278.7 0 0 0-11.64-79.94A254.86 254.86 0 0 0 256 0C114.62 0 0 114.58 0 256z"
                                            opacity="1" data-original="#74da7f" class=""></path>
                                        <path fill="#FFFFFF"
                                            d="M402 213.58 248.13 375.17a45.16 45.16 0 0 1-32.48 14h-.2a45.11 45.11 0 0 1-32.4-13.71l-81.65-84.1a45.14 45.14 0 1 1 64.78-62.87l48.95 50.42 121.49-127.58A45.14 45.14 0 1 1 402 213.58z"
                                            opacity="1" data-original="#ffffff" class=""></path>
                                    </g>
                                </svg>
                            </label>
                        </li>
                        <li>
                            <input type="checkbox" wire:click="updateStatus('advanced')" id="advanced_completed"
                                class="hidden peer" @if ($advanced_completed) Checked @endif
                                @if (!$intermediate_completed) disabled @endif
                                @if (!$beginner_completed) disabled @endif>
                            <label for="advanced_completed"
                                class="inline-flex items-center font-semibold text-sm justify-between w-full px-3 py-1.5 text-gray-500 bg-white border-2 border-gray-200 rounded-xl cursor-pointer  peer-checked:border-green-600 hover:text-gray-600  peer-checked:text-green-600  hover:bg-gray-50 ">
                                Advanced Completed
                                <svg class="ml-2 @if (!$advanced_completed) hidden @endif"
                                    xmlns="http://www.w3.org/2000/svg" version="1.1"
                                    xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" x="0"
                                    y="0" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512"
                                    xml:space="preserve" class="">
                                    <g>
                                        <path fill="#2AD352"
                                            d="M256 0C114.62 0 0 114.58 0 256s114.62 256 256 256 256-114.65 256-256S397.38 0 256 0z"
                                            opacity="1" data-original="#2ad352" class=""></path>
                                        <path fill="#74DA7F"
                                            d="M0 256a254.87 254.87 0 0 0 30.49 121.23 278.76 278.76 0 0 0 78.73 11.29c153.9 0 278.66-124.76 278.66-278.66a278.7 278.7 0 0 0-11.64-79.94A254.86 254.86 0 0 0 256 0C114.62 0 0 114.58 0 256z"
                                            opacity="1" data-original="#74da7f" class=""></path>
                                        <path fill="#FFFFFF"
                                            d="M402 213.58 248.13 375.17a45.16 45.16 0 0 1-32.48 14h-.2a45.11 45.11 0 0 1-32.4-13.71l-81.65-84.1a45.14 45.14 0 1 1 64.78-62.87l48.95 50.42 121.49-127.58A45.14 45.14 0 1 1 402 213.58z"
                                            opacity="1" data-original="#ffffff" class=""></path>
                                    </g>
                                </svg>
                            </label>
                        </li>

                    </ul>
                @endif


                {{-- modal body --}}
                <div class="">
                    @if ($roadmapContent)
                        {!! str_replace(['```html', '```'], ['', ''], $roadmapContent) !!}
                    @else
                        {!! str_replace(['```html', '```'], ['', ''], $viewRoadmapContent) !!}
                    @endif

                </div>
                <br>
                @if ($roadmapContent)
                    <div class="modal-footer py-4 flex items-center justify-end">
                        <button wire:click="saveRoadmap" type="button"
                            class=" flex items-center bg-gradient-to-r from-indigo-500  to-blue-500  hover:bg-right hover:bg-cover hover:bg-no-repeat hover:bg-gradient-to-r hover:from-blue-500 hover:to-indigo-500 text-white hover:shadow-md rounded-2xl py-2 px-12 text-center transition-all duration-700 border border-indigo-500">
                            Save <span wire:loading class="mx-1 fill-current"><svg width="20" height="20"
                                    fill="currentColor" class="mr-2 animate-spin" viewBox="0 0 1792 1792"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M526 1394q0 53-37.5 90.5t-90.5 37.5q-52 0-90-38t-38-90q0-53 37.5-90.5t90.5-37.5 90.5 37.5 37.5 90.5zm498 206q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-704-704q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm1202 498q0 52-38 90t-90 38q-53 0-90.5-37.5t-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-964-996q0 66-47 113t-113 47-113-47-47-113 47-113 113-47 113 47 47 113zm1170 498q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-640-704q0 80-56 136t-136 56-136-56-56-136 56-136 136-56 136 56 56 136zm530 206q0 93-66 158.5t-158 65.5q-93 0-158.5-65.5t-65.5-158.5q0-92 65.5-158t158.5-66q92 0 158 66t66 158z">
                                    </path>
                                </svg></span>
                        </button>
                    </div>
                @endif
            </div>
        </div>
    </div>

</div>
